### ISSUE TITLE
Add Bonus column

### ISSUE THREAD

**Issue by on247** [bustabit/issues#11]
![image](https://user-images.githubusercontent.com/5596081/30832676-901459c4-a211-11e7-8365-d49e6cfe7ba6.png)

![image](https://user-images.githubusercontent.com/5596081/30832900-83cb6a1c-a212-11e7-983f-fb6e1c2dff24.png)

Show bonus in bits and (%)

**Comment by RHavar** [comment]
This version isn't going to have bonuses, that'll be released as a separate game for people who want to play competitively :D
