### ISSUE TITLE
Missing docs on new script window

### ISSUE THREAD

**Issue by on247** [bustabit/issues#8]
![image](https://user-images.githubusercontent.com/5596081/30832245-ff95a52a-a20f-11e7-9064-2c66a931871d.png)
Yeah , i know the preloaded scripts are documented , but what if someone just goes ahead to create a new one

Also a explanation about the config object and UI somewhere would be nice.

**Comment by RHavar** [comment]
Here's the docs:
https://github.com/bustabit/autobet

But yeah, needs to be linked

**Comment by AllAlphacoders** [comment]
Error when joining the game... NOT_VALID_TOKEN

Ryan can you helping me solving this error? on bustabit script
